name: nf-core-rrna-ampliseq-1.0
channels:
  - anaconda
  - qiime2/label/r2018.6
  - qiime2
  - conda-forge
  - defaults
  - bioconda
  - biocore
dependencies:
  - fastqc=0.11.8 #newest version
  - multiqc=1.6 #newest version
  - unzip=6.0 #required for silva unzippping
  - r-rmarkdown=1.10
  - conda-forge::ncurses=5.9
  - msgpack-python=0.5.6 #This was part of QIIME2 YAML
  #Everything below here was copied from QIIME2 YAML file (2018-08 version) including dependencies for QIIME2 - DO NOT UPDATE
  - bioconductor-biobase=2.38.0
  - bioconductor-biocgenerics=0.24.0
  - bioconductor-biocparallel=1.12.0
  - bioconductor-biostrings=2.46.0
  - bioconductor-dada2=1.6.0
  - bioconductor-delayedarray=0.4.1
  - bioconductor-genomeinfodb=1.14.0
  - bioconductor-genomeinfodbdata=1.0.0
  - bioconductor-genomicalignments=1.14.1
  - bioconductor-genomicranges=1.30.3
  - bioconductor-iranges=2.12.0
  - bioconductor-rsamtools=1.30.0
  - bioconductor-s4vectors=0.16.0
  - bioconductor-shortread=1.36.0
  - bioconductor-summarizedexperiment=1.8.0
  - bioconductor-xvector=0.18.0
  - bioconductor-zlibbioc=1.24.0
  - blast=2.6.0
  - cutadapt=1.16
  - deblur=1.0.4
  - fasttree=2.1.10
  - mafft=7.310
  - raxml=8.2.10
  - sortmerna=2.0
  - vsearch=2.7.0
  - xopen=0.3.2
  - gneiss=0.4.4
  - unifrac=0.9.2
  - asn1crypto=0.24.0
  - backcall=0.1.0
  - bibtexparser=1.0.1
  - bleach=2.1.3
  - bokeh=0.12.15
  - boost=1.64.0
  - boost-cpp=1.64.0
  - bzip2=1.0.6
  - ca-certificates=2018.4.16
  - cachecontrol=0.12.4
  - cairo=1.14.10
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - cryptography=2.2.1
  - curl=7.60.0
  - cycler=0.10.0
  - cython=0.28.3
  - dbus=1.13.0
  - decorator=4.3.0
  - emperor=1.0.0beta16
  - entrypoints=0.2.3
  - expat=2.2.5
  - fastcluster=1.1.25
  - fontconfig=2.12.6
  - freetype=2.8.1
  - future=0.16.0
  - gettext=0.19.8.1
  - glib=2.55.0
  - gmp=6.1.2
  - graphite2=1.3.11
  - gsl=2.1
  - gst-plugins-base=1.8.0
  - gstreamer=1.8.0
  - h5py=2.7.0
  - harfbuzz=1.7.6
  - hdf5=1.8.17
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.7
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jedi=0.12.0
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - krb5=1.14.6
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.34
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxcb=1.13
  - libxml2=2.9.8
  - lockfile=0.12.2
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - msgpack-python=0.5.6
  - natsort=5.3.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nose=1.3.7
  - notebook=5.5.0
  - openssl=1.0.2o
  - packaging=17.1
  - pandas=0.23.1
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso=0.2.1
  - patsy=0.5.0
  - pcre=8.39
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pigz=2.3.4
  - pip=9.0.3
  - pixman=0.34.0
  - prompt_toolkit=1.0.15
  - psutil=5.4.6
  - ptyprocess=0.6.0
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pysocks=1.6.8
  - python=3.5.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - pyyaml=3.12
  - pyzmq=17.0.0
  - conda-forge::qt=5.6.2
  - r-assertthat=0.2.0
  - r-base=3.4.1
  - r-bh=1.66.0_1
  - r-bitops=1.0_6
  - r-cli=1.0.0
  - r-colorspace=1.3_2
  - r-crayon=1.3.4
  - r-data.table=1.11.4
  - r-dichromat=2.0_0
  - r-digest=0.6.15
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.0
  - r-ggplot2=2.2.1
  - r-glue=1.2.0
  - r-gtable=0.2.0
  - r-hwriter=1.3.2
  - r-labeling=0.3
  - r-lambda.r=1.2
  - r-lattice=0.20_34
  - r-latticeextra=0.6_28
  - r-lazyeval=0.2.1
  - r-magrittr=1.5
  - r-mass=7.3_48
  - r-matrix=1.2_14
  - r-matrixstats=0.53.1
  - r-munsell=0.5.0
  - r-pillar=1.2.1
  - r-plyr=1.8.4
  - r-r6=2.2.2
  - r-rcolorbrewer=1.1_2
  - r-rcpp=0.12.15
  - r-rcppparallel=4.4.0
  - r-rcurl=1.95_4.8
  - r-reshape2=1.4.3
  - r-rlang=0.2.1
  - r-scales=0.5.0
  - r-snow=0.4_2
  - r-stringi=1.1.7
  - r-stringr=1.3.0
  - r-tibble=1.4.2
  - r-utf8=1.1.3
  - r-viridislite=0.3.0
  - readline=7.0
  - requests=2.19.1
  - seaborn=0.8.1
  - send2trash=1.5.0
  - setuptools=39.2.0
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - sqlite=3.20.1
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.2
  - traitlets=4.3.2
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5
  - wheel=0.31.0
  - widgetsnbextension=3.2.1
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.3
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - intel-openmp=2018.0.3
  - libgcc=7.2.0
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - libstdcxx-ng=7.2.0
  - mkl=2018.0.3
  - numpy=1.12.1
  - scikit-learn=0.19.1
  - scipy=0.19.1
  - wget=1.19.5
  - q2-alignment=2018.6.0
  - q2-composition=2018.6.0
  - q2-cutadapt=2018.6.0
  - q2-dada2=2018.6.0
  - q2-deblur=2018.6.0
  - q2-demux=2018.6.0
  - q2-diversity=2018.6.0
  - q2-emperor=2018.6.0
  - q2-feature-classifier=2018.6.0
  - q2-feature-table=2018.6.0
  - q2-gneiss=2018.6.0
  - q2-longitudinal=2018.6.0
  - q2-metadata=2018.6.0
  - q2-phylogeny=2018.6.0
  - q2-quality-control=2018.6.1
  - q2-quality-filter=2018.6.0
  - q2-sample-classifier=2018.6.0
  - q2-taxa=2018.6.0
  - q2-types=2018.6.0
  - q2-vsearch=2018.6.0
  - q2cli=2018.6.0
  - q2templates=2018.6.0
  - qiime2=2018.6.0
  - biom-format=2.1.6
  - ijson=2.3
  - scikit-bio=0.5.1
  - tzlocal=1.3
  
